language: groovy

jdk:
  - oraclejdk8

sudo: required

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Avoid Travis to run the default of "gradle assemble" at this stage by
# already building and installing the plugin here.
install:
  - ./gradlew plugin:publishToMavenLocal

script:
  - ./gradlew --stacktrace plugin:check
  - ./gradlew example:assemble
